### ISSUE TITLE
Vendor ID is missing, causing an out-of-index crash

### ISSUE THREAD

**Issue by amomchilov** [mkoreneff/iommu_info_generate#1]
Heyo! I wanted to contribute data for my board (ASRock B450M Pro4), but I get a crash:

```
Traceback (most recent call last):
  File "/root/iommu_info_generate/generate_data.py", line 174, in <module>
    main()
  File "/root/iommu_info_generate/generate_data.py", line 142, in main
    vendorid = json.loads(r.text)[0].get("vendorid")
IndexError: list index out of range
```

(`r.text` is just `[]`)

I guess the ASRock vendor ID isn't registered? In any case, the client should handle that gracefully :)

**Comment by mkoreneff** [comment]
Thanks for reporting the issue. I found some other vendors that don't have registered id's. 
I'll put together a patch to the script with a DEBUG mode. Hopefully it will expose the vendor id that i can add to the db.

**Comment by mkoreneff** [comment]
Can you send me the output of 
`cat /sys/devices/virtual/dmi/id/board_vendor`

**Comment by mkoreneff** [comment]
This will handle the failed lookup - d7fbe43b92782b18e638e17a02d5ab3564b7bc8f - but there is still some work to support your setup. 
If you can paste me the output of these commands, I can track down the error. 
`cat /sys/devices/virtual/dmi/id/board_vendor`
`cat /sys/devices/virtual/dmi/id/bios_vendor`

**Comment by amomchilov** [comment]
@mkoreneff
