### ISSUE TITLE
Board Version is Blank

### ISSUE THREAD

**Issue by VincentSaelzler** [mkoreneff/iommu_info_generate#2]
For my motherboard, the `/sys/devices/virtual/dmi/id/board_version` file is blank.
```sh
# python3 generate_data.py
request error: Bad Request
{"board":{"version":["This field may not be blank."]}}
```
```sh
# cat /sys/devices/virtual/dmi/id/...
board_name
B550 Phantom Gaming 4
board_vendor
ASRock
board_version

bios_date
08/02/2021
bios_release
5.17
bios_vendor
American Megatrends International, LLC.
bios_version
P2.10
```

**Comment by mkoreneff** [comment]
Thanks for raising the issue, I'll get a fix out soon. Having blank or missing fields in the hardware is more common than I expected.

**Comment by mkoreneff** [comment]
Could you please send the output of `ls /sys/devices/virtual/dmi/id/`
and if there are product keys send  `cat /sys/devices/virtual/dmi/id/product_*`

**Comment by VincentSaelzler** [comment]
sorry @mkoreneff, I sold this PC over the weekend.

**Comment by VincentSaelzler** [comment]
I will be setting up a new one with another B550 motherboard. Will raise an issue if one comes up, or otherwise be posting to the database!

**Comment by mkoreneff** [comment]
Not a problem, I can work with the `board_name` as shown. Should be fine to
use that instead of `board_version`

**Comment by mkoreneff** [comment]
I made a release on the API, board_version is now optional
