### ISSUE TITLE
Use chassis_type for better naming of Laptops/Notebooks

### ISSUE THREAD

**Issue by jacobhuggins** [mkoreneff/iommu_info_generate#3]
On my Razer Blade 15 board_name returns "DA550" which isn't very descriptive. I suggest querying chassis_type to determine if a device is a laptop/notebook and then if it is use product_name instead. Asking the user if their device is a notebook/laptop would be another solution.

For example on my Razer Blade 15, chassis_type returns "10" which is the value for "Notebook". Printing out product_name returns with "Blade 15 Base Model (Early 2020) - RZ09-0328"

[On page 42 is a list of chassis_type values.](https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.6.0.pdf)

**Comment by mkoreneff** [comment]
Looked into this a bit more, and you're definitely right, things look different for Notebooks. I'll make some modifications to cater for `chassis_type == 10`. Looks like parsing `product_family` or ` product_version` seems like the right thing to do; let me know if there are any objections or suggestions.

**Comment by mkoreneff** [comment]
this is resolved in f5d5ba5
