### ISSUE TITLE
Cannot find vendor ID for Supermicro motherboard

### ISSUE THREAD

**Issue by chenxiaolong** [mkoreneff/iommu_info_generate#4]
When I try to run `generate_data.py` on a system with a Supermicro X13SAE-F motherboard, I'm getting this output:

```
list index out of range while trying to lookup Mainboard vendorid for: Supermicro
Please report this problem and supply the output of
cat /sys/devices/virtual/dmi/id/board_vendor
request error: Bad Request
{"board":{"board_vendor":{"vendorid":["This field may not be blank."]}}}
please report this issue: https://github.com/mkoreneff/iommu_info_generate/issues/new/choose
```

I've attached a tarball containing everything under `/sys/devices/virtual/dmi/id/`: [dmi_id.tar.gz](https://github.com/mkoreneff/iommu_info_generate/files/10144480/dmi_id.tar.gz)

Thanks!

**Comment by mkoreneff** [comment]
thanks for pointing this out, I have added an entry for Supermicro; the script should pass now.
https://iommu.info/api/vendor/Supermicro shows the correct data so we're good to go here.

**Comment by chenxiaolong** [comment]
Thanks! I'm able to successfully submit the data now.
